version: 1.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build: nuget restore

build:
  project: Grikly.sln
  publish_nuget: true  

artifacts:
  - path: 'out\*.nupkg'
